### ISSUE TITLE
Support templates insted only of secondary entity. 

### ISSUE THREAD

**Issue by mefistofelis** [selvalt7/modern-circular-gauge#10]
Hi, excellent card and clear design. I would be delighted if we could support templates as a secondary entity. It will give this card way more flexibility.

**Comment by selvalt7** [comment]
Interesting, 
I will look into implementing that.

**Comment by mefistofelis** [comment]
Awesome thx

**Comment by mefistofelis** [comment]
Thx for adding that, but what i meant was something similar like the mushroom template card. So i meant the ability to put  sth like this 
secondary: >
  {{states('sensor.daily_consumption')|round(1)}}

**Comment by selvalt7** [comment]
I've made some changes in the PR based on your idea.
In the future, leave comments in the corresponding PR so it’s better organized.
