### ISSUE TITLE
Using a template for the 'max' setting?

### ISSUE THREAD

**Issue by erikgeurts** [selvalt7/modern-circular-gauge#14]
I'd like to ask if there's any way to set the 'max' option of a gauge using a template, for example to use the value in an input_number helper. The reason is that I would like to be able to display gauges that show progress towards a maximum value that can vary on a regular basis or perhaps even through an automation.

For example, let's say I've got an input_number helper that indicates how many kWh I want to add to my EV battery during the next or the current charging session. Let's also say I have a sensor that counts how many kWh have already been added. Having 'max' use the input_number would mean the gauge always shows how the current charging session is progressing.

Obviously, templating like this could cause issues if the input_number would become negative or if 'max' is lower than the current value, but that would be mostly 'user error'.

**Comment by selvalt7** [comment]
For now, there isn't any way to use templates in min and max options, but it shouldn't be hard to implement that, so I will look into this.

**Comment by erikgeurts** [comment]
> For now, there isn't any way to use templates in min and max options, but it shouldn't be hard to implement that, so I will look into this before the stable release.

Very nice that you're willing to consider this. Please let me know if I can help in any way!

**Comment by erikgeurts** [comment]
> Maybe it would be worth adding the `entity` option as a template too?

For me, personally, not so much, but I could see how it might be for other users/use cases. I'd say perhaps start by adding template support for min and max, and then at a later date, perhaps based on user feedback, consider adding template support for other options?

By the way, I could live with template support for min and max in yaml only, to begin with. I don't really know if you've enabled UI editing for templating the secondary entity already, if so you probably know how to offer min and max templating in the UI as well.

**Comment by selvalt7** [comment]
OK, so for now I will add template support for `min` and `max`. 

Currently, templates are YAML only as I couldn't think of a good UI. Maybe in the future, I will add UI support.
