### ISSUE TITLE
Pasting Hex segment color codes doesn't work

### ISSUE THREAD

**Issue by erikgeurts** [selvalt7/modern-circular-gauge#24]
Recently, I was defining the segments and colors of a gauge, and I wanted to use a set of Hex color codes. But to my surprise, I was unable to paste them into the color field for a segment.

For example, I have this color code #213555 and I'm trying to paste it into the UI while defining a segment. I click the colored bar, and change the entry mode to hex, and then I click with my mouse cursor on the default value #000000. This gets the value selected, but when I use Ctrl-V to paste the value from my clipboard, all that happens is that the hex color for black disappears. All that remains is a flashing cursor.

I checked to make sure the value is actually on my clipboard by pasting it in a blank email.

Typing the hex color code manually works, just not pasting it.

**Comment by selvalt7** [comment]
Color picker dialog is handled by web browser.
This seems to be an issue in the browser itself not the card.

**Comment by erikgeurts** [comment]
That's interesting, I wasn't aware of that! Thanks for enlightening me.

Still strange that the browser in Chrome OS (most recent version) doesn't handle this properly.
