### ISSUE TITLE
Card scaling

### ISSUE THREAD

**Issue by diedrichg** [selvalt7/modern-circular-gauge#6]
It would be wonderful if the card supported the new Sections Layout Precise Mode. Ideally, allowing the graph to stretch or compress for the given card size would be best, and yet keeping the text size proportional so that it doesn't stretch and all it does is zoom to fit the size of the card.

**Comment by selvalt7** [comment]
The card will support the new Precise mode but unfortunately gauge will keep constant aspect ratio for design reasons.
As for the text I will redo it for better sizing.

**Comment by somansch** [comment]
Would be great to allow smaller scaling to show 3 cards in a row, so a grid of 4 (3x4=12) instead of 6:
![image](https://github.com/user-attachments/assets/34d695e5-c69d-400f-ae9d-46da4d7d6c50)
